statustext = "Hava Durumu Bilgisi Alınırken Lütfen Bekleyin..."
nostatustext = ""
comboboxtext = "Lütfen bir şehir seçiniz"
citys = [
    "Adana",
    "Tokyo",
    "Delhi",
    "Shanghai",
    "Sao Paulo",
    "Mumbai",
    "Mexico City",
    "Beijing",
    "Osaka",
    "Cairo",
    "New York City",
    "Dhaka",
    "Karachi",
    "Buenos Aires",
    "Denizli",
    "Istanbul",
    "Chongqing",
    "Kolkata",
    "Lagos",
    "Kinshasa",
    "Manila",
    "Tianjin",
    "Rio de Janeiro",
    "Guangzhou",
    "Los Angeles",
    "Moscow",
    "Shenzhen",
    "Lahore",
    "Bangalore",
    "Kastamonu",
    "Paris",
    "Bogota",
    "Jakarta",
    "Chennai",
    "Lima",
    "Bangkok",
    "Seoul",
    "Nagoya",
    "Hyderabad",
    "London",
    "Tehran",
    "Ordu",
    "Chicago",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Ho Chi Minh City",
    "Luanda",
    "Ahmedabad",
    "Kuala Lumpur",
    "Hangzhou",
    "Hong Kong",
    "Quanzhou"
]



